services:

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      GATEWAY_PORT: "3000"
      USER_SERVICE_URL: http://user-service:3001
      PRODUCT_SERVICE_URL: http://product-service:3002
      ORDER_SERVICE_URL: http://order-service:3003
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - campusconnect-network

  user-service:
    image: campusconnect-user-service:latest
    container_name: user-service
    environment:
      USER_SERVICE_PORT: "3001"
      MONGO_URI: "${MONGO_ATLAS_URI}/userdb?retryWrites=true&w=majority"
    networks:
      - campusconnect-network

  product-service:
    image: campusconnect-product-service:latest
    container_name: product-service
    environment:
      PRODUCT_SERVICE_PORT: "3002"
      MONGO_URI: "${MONGO_ATLAS_URI}/productdb?retryWrites=true&w=majority"
    networks:
      - campusconnect-network

  order-service:
    image: campusconnect-order-service:latest
    container_name: order-service
    environment:
      ORDER_SERVICE_PORT: "3003"
      MONGO_URI: "${MONGO_ATLAS_URI}/orderdb?retryWrites=true&w=majority"
      USER_SERVICE_URL: http://user-service:3001
      PRODUCT_SERVICE_URL: http://product-service:3002
    depends_on:
      - user-service
      - product-service
    networks:
      - campusconnect-network

networks:
  campusconnect-network:
    external: true