services:

  # ==========================================
  # USER SERVICE
  # ==========================================
  - type: web
    name: user-service
    runtime: docker
    plan: free
    region: singapore

    dockerfilePath: ./user-service/Dockerfile
    dockerContext: ./user-service

    envVars:
      - key: USER_SERVICE_PORT
        value: "10000"

      - key: MONGO_DATABASE
        value: "userdb"

      - key: MONGO_URI
        sync: false


  # ==========================================
  # API GATEWAY
  # ==========================================
  - type: web
    name: api-gateway
    runtime: docker
    plan: free
    region: singapore

    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway

    healthCheckPath: /health

    envVars:
      - key: GATEWAY_PORT
        value: "10000"

      - key: USER_SERVICE_URL
        fromService:
          type: web
          name: user-service
          property: hostport