spring.application.name=order-service

server.port=${PORT:${ORDER_SERVICE_PORT:3003}}

spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27019/orderdb}
spring.mongodb.database=${MONGO_DATABASE:orderdb}
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27019/orderdb}

spring.data.mongodb.auto-index-creation=true

USER_SERVICE_URL=${USER_SERVICE_URL:http://localhost:3001}
PRODUCT_SERVICE_URL=${PRODUCT_SERVICE_URL:http://localhost:3002}