spring.application.name=product-service

server.port=${PORT:${PRODUCT_SERVICE_PORT:3002}}

spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27018/productdb}
spring.mongodb.database=${MONGO_DATABASE:productdb}
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27018/productdb}

spring.data.mongodb.auto-index-creation=true